### ISSUE TITLE
No longer supports Fluture

### ISSUE THREAD

**Issue by AntonStrand** [articulate/redux-future2#1]
Since the new release of Fluture (v12) the `fork` method was removed and therefore will not be considered a valid future according to the implementation of this middleware.

Fluture provides both `isFluture` and `fork` as functions which makes a fix trivial but it would mean that Fluture has to be a dependency. Which might seem a bit excessive.

Either way, I thought I'll let you know in case you wanted to do something about it or just add a disclaimer in the readme. 

Here is an example I wrote explaining the problem and possible solution. https://runkit.com/antonstrand/5dd50b6b45205a0013ae5cb6

**Comment by mgreystone** [comment]
Thanks for the report. At Articulate, we rarely use Fluture ourselves. Instead of adding Fluture as a dependency, i think we'll make a note of this in the documentation.

**Comment by AntonStrand** [comment]
Cool, I thought I'll just let you know. A bit off-topic, but what do you use instead? Promises or another Future implementation?

**Comment by rpearce** [comment]
@AntonStrand https://crocks.dev/docs/crocks/Async.html
